### ISSUE TITLE
Add ci-scripts - 12

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-virtualization-tests#13]
[Auto generated]
Number: [#12]

**Comment by redhat-qe-bot2** [comment]
[1;38mopenshift-virtualization-tests[1;0m(9cRpT)[PR 12]: Closing issue for PR: Add ci-scripts.
PR was closed.

**Comment by redhat-qe-bot2** [comment]
[1;38mopenshift-virtualization-tests[1;0m(9cRpT)[PR 12]: Closing issue for PR: Add ci-scripts.
PR was closed.

**Comment by redhat-qe-bot2** [comment]
[1;38mopenshift-virtualization-tests[1;0m(9cRpT)[PR 12]: Closing issue for PR: Add ci-scripts.
PR was closed.

**Comment by redhat-qe-bot2** [comment]
[1;38mopenshift-virtualization-tests[1;0m(9cRpT)[PR 12]: Closing issue for PR: Add ci-scripts.
PR was closed.

**Comment by redhat-qe-bot2** [comment]
[1;38mopenshift-virtualization-tests[1;0m(9cRpT)[PR 12]: Closing issue for PR: Add ci-scripts.
PR was closed.

**Comment by redhat-qe-bot2** [comment]
[1;38mopenshift-virtualization-tests[1;0m(9cRpT)[PR 12]: Closing issue for PR: Add ci-scripts.
PR was closed.
