### ISSUE TITLE
Update OWNERS - 8

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/openshift-virtualization-tests#9]
[Auto generated]
Number: [#8]

**Comment by redhat-qe-bot1** [comment]
[1;36mopenshift-virtualization-tests[1;0m(47Zq6)[PR 8]: Closing issue for PR: Update OWNERS.
PR was closed.

**Comment by redhat-qe-bot1** [comment]
[1;36mopenshift-virtualization-tests[1;0m(47Zq6)[PR 8]: Closing issue for PR: Update OWNERS.
PR was closed.

**Comment by redhat-qe-bot1** [comment]
[1;36mopenshift-virtualization-tests[1;0m(47Zq6)[PR 8]: Closing issue for PR: Update OWNERS.
PR was closed.

**Comment by redhat-qe-bot1** [comment]
[1;36mopenshift-virtualization-tests[1;0m(47Zq6)[PR 8]: Closing issue for PR: Update OWNERS.
PR was closed.

**Comment by redhat-qe-bot1** [comment]
[1;36mopenshift-virtualization-tests[1;0m(47Zq6)[PR 8]: Closing issue for PR: Update OWNERS.
PR was closed.

**Comment by redhat-qe-bot1** [comment]
[1;36mopenshift-virtualization-tests[1;0m(47Zq6)[PR 8]: Closing issue for PR: Update OWNERS.
PR was closed.
